[package]
name = "veridian"
version = "0.1.0"
authors = ["Vivek Malneedi <vivekmalneedi@gmail.com>"]
edition = "2018"

[features]
slang = ["veridian_slang"]

[dependencies]
log = "0.4.27"
tower-lsp = "0.20.0"
flexi_logger = "0.30.1"
ropey = "1.6.1"
tokio = { version = "1.44.2", features = ["macros", "io-std", "rt-multi-thread"] }
path-clean = "1.0.1"
pathdiff = "0.2.3"
walkdir = "2.5.0"
serde_yaml = "0.9.34"
anyhow = "1.0.98"
serde = "1.0.219"
which = "7.0.3"
regex = "1.11.1"
structopt = "0.3.26"
strum = "0.27.1"
strum_macros = "0.27.1"
tree-sitter = "0.25.3"
tree-sitter-systemverilog = { path = "../tree-sitter-systemverilog" }
streaming-iterator = "0.1.9"

[dev-dependencies]
tempdir = "0.3.7"

[dependencies.veridian_slang]
optional = true
path = "veridian-slang"
